// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALChDwsQBUUlmvTjzUIUGwqXWjGaExwWY',
    appId: '1:627998248999:web:ede0d606dd66b76f7abe02',
    messagingSenderId: '627998248999',
    projectId: 'brew-crew-526bd',
    authDomain: 'brew-crew-526bd.firebaseapp.com',
    storageBucket: 'brew-crew-526bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9vaUYETaVEKjITgMf44EDveHjOskVj8',
    appId: '1:627998248999:android:b3b414425790b88d7abe02',
    messagingSenderId: '627998248999',
    projectId: 'brew-crew-526bd',
    storageBucket: 'brew-crew-526bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOP9b3z3N4IbFaNnSOWYlsRXDKNgWJ3Zc',
    appId: '1:627998248999:ios:d3b47a4de46cb8ad7abe02',
    messagingSenderId: '627998248999',
    projectId: 'brew-crew-526bd',
    storageBucket: 'brew-crew-526bd.appspot.com',
    iosClientId: '627998248999-2lvm79sh989cr5ah6hskab8jijfr7j3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOP9b3z3N4IbFaNnSOWYlsRXDKNgWJ3Zc',
    appId: '1:627998248999:ios:d3b47a4de46cb8ad7abe02',
    messagingSenderId: '627998248999',
    projectId: 'brew-crew-526bd',
    storageBucket: 'brew-crew-526bd.appspot.com',
    iosClientId: '627998248999-2lvm79sh989cr5ah6hskab8jijfr7j3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
